### ISSUE TITLE
ปัญหาที่พบ แนวทางการแก้ไข

### ISSUE THREAD

**Issue by 660610792WarangkanaJitwarangkana** [itspornpailin/Formoonteller#13]
เมื่อตรวจพบปัญหาที่เกิดขึ้นเกี่ยวกับโค้ดจะทำการแจ้งไว้ในช่องนี้เพื่อให้ผู้ที่รับผิดชอบส่วนต่างๆแก้ไขปัญหานั้นๆ
และจดบันทึกการแก้ไขรวมถึงผลของการแก้ไขไว้

**Comment by 660610792WarangkanaJitwarangkana** [comment]
เช็คปัญหารอบที่ 1 : ชื่อที่มีการเว้นวรรค
Issue : Enter Name & Gender

ปัญหา : หากกรอกชื่อที่มีการเว้นวรรคจะแสดงผลแค่ช่วงที่ยังไม่ได้เว้นวรรค

วิธีการแก้ไข 1 : การใช้ get line เข้ามาช่วยแต่ฟังก์ชันนี้ก็มีข้อจำกัดอยู่ ได้ทำการประยุกต์ใช้ทำให้สามารถแสดงผลได้ตามปกติ
date : 21/02/2024

**Comment by itspornpailin** [comment]
ปัญหาการเขียนโค้ด Randomizer:
คำสั่ง rand() ไม่สามารถสุ่มได้ random เท่าที่ต้องการ

แก้ปัญหาโดยการอ้างอิงจาก 
- https://en.cppreference.com/w/cpp/numeric/random/random_device
- https://codeforces.com/blog/entry/61587?locale=ru
ซึ่งใช้ 
random_device rd;
mt19937 rng(rd());
ในการสุ่มแทน

**Comment by 660610792WarangkanaJitwarangkana** [comment]
เช็คปัญหารอบที่ 2 : การสุ่มไพ่
Issue : มีการสุ่มไพ่แค่รอบแรก รอบถัดไปได้ผลลัพธ์เดิม

ปัญหา : การใช้ฟังก์ชั่น rand ได้ทำการเขียนฟังก์ชั่นรัน 2 แบบ สามารถประยุกตืใช้ตามความต้องการได้

วิธีการแก้ไข 1 : แก้ไข return
date : 27/02/2024
